"""Initial migration.

Revision ID: b4955c92275c
Revises: 
Create Date: 2021-12-19 11:44:39.943502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4955c92275c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_mean', sa.Float(), nullable=True),
    sa.Column('temperature_std_dev', sa.Float(), nullable=True),
    sa.Column('humidity_mean', sa.Float(), nullable=True),
    sa.Column('humidity_std_dev', sa.Float(), nullable=True),
    sa.Column('pressure_mean', sa.Float(), nullable=True),
    sa.Column('pressure_std_dev', sa.Float(), nullable=True),
    sa.Column('light_mean', sa.Float(), nullable=True),
    sa.Column('light_std_dev', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
